### ISSUE TITLE
belt ewnd9:provision --setup npm

### ISSUE THREAD

**Issue by mini890** [ewnd9/dotfiles#2]
There is an error during the "belt ewnd9:provision --setup npm" command.

The error occurs when installing cache-fs.

I can't seem to find any package with that name. Could it have been removed?

Error log:

$ npm install --global cache-fs
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for cache-fs

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/miguel/.npm/_logs/2019-07-12T19_54_51_125Z-debug.log
(node:22860) UnhandledPromiseRejectionWarning: Error: Command failed: npm install --global cache-fs
    at makeError (/home/miguel/dotfiles/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/home/miguel/dotfiles/node_modules/execa/index.js:277:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mini890** [comment]
Same happens with the npm package "generator-ewnd9-eslint"

**Comment by mini890** [comment]
Nevermind. See this when you can. Closing issue to clean up open issues on my side.
